name: hard_localization
description: "Easy and Fast internationalization and localization your Flutter Apps, this package simplifies the internationalization process."
version: 0.0.1
homepage: https://github.com/michaelnabil/hard_localization

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ">=0.19.0"
  args: ^2.5.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2

flutter: