name: Format, Analyze and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0" # runs the CI weekly

jobs:
  default_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - name: Flutter get
        run: flutter pub get

      - name: Dart format
        run: dart format --set-exit-if-changed .

      - name: Flutter analyze
        run: flutter analyze .

      - name: Flutter test
        run: flutter test --no-pub --coverage

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash | bash
